// <auto-generated />
namespace moviewatch.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class sql_membership_genre : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sql_membership_genre));
        
        string IMigrationMetadata.Id
        {
            get { return "201709090935002_sql_membership_genre"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
